config/routes.rb
FoodSafeNet::Application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'

  devise_for :users

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  match '/laws/search' => 'laws#search'
  match '/servers/search_company' => 'servers#search_company'
  match '/servers/search_product' => 'servers#search_product'
  match 'organ' => 'organ#show'
  resources :comments, :only => [:create]
  resources :laws
  resources :gov_infos
  resources :public_infos
  resources :posts
  resources :products
  resources :reports, :only => [:index, :create, :query] do
    collection do
      post :query
    end
  end
  match 'servers' => 'servers#index'
  resources :integritys

  match '/signin' => 'sessions#new'

  root :to => "home_page#show"

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  # attr_accessible :title, :body
  belongs_to :user
  belongs_to :post

  attr_accessible :body, :user_id, :post_id
  validate :body, :presence => true
  validate :user_id, :presence => true
  validate :post_id, :presence => true
end

app/models/company.rb
class Company < ActiveRecord::Base
  attr_accessible :legal_person, :license_no, :license_project, :name, :produce_address, :register_address, :valid_for
end

app/models/gov_info.rb
class GovInfo < ActiveRecord::Base
  attr_accessible :content, :name, :info_type
end

app/models/integrity.rb
class Integrity < ActiveRecord::Base
  attr_accessible :content, :info_type, :title
end

app/models/law.rb
class Law < ActiveRecord::Base
  attr_accessible :content, :law_type, :title
end

app/models/organ.rb
class Organ < ActiveRecord::Base
  attr_accessible :content, :title
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :content, :title, :user_id

  has_many :comments
  belongs_to :user

  validate :content, :presence => true
  validate :title, :presence => true
  validate :user_id, :presence => true

end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :company_address, :company_name, :health_function, :license_no, :name
end

app/models/public_info.rb
class PublicInfo < ActiveRecord::Base
  attr_accessible :content, :file_number, :index_number, :organ, :title, :info_type
end

app/models/report.rb
class Report < ActiveRecord::Base
  attr_accessible :content, :no, :status, :title, :user_email, :user_name, :user_phone

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts, :dependent => :delete_all
  has_many :comments, :dependent => :delete_all

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :name, :password_confirmation, :remember_me
  # attr_accessible :title, :body
  validate :email, :presence => true, :uniqueness => true
  validate :password, :presence => true
  validate :name, :presence => true
end

app/controllers/public_infos_controller.rb
#encoding: utf-8

class PublicInfosController < ApplicationController
  def index
    @info_types = PublicInfo.select(:info_type).uniq.map(&:info_type)
    if params[:info_type] == nil
      @public_infos = PublicInfo.where("info_type = '部门文件'").page(params[:page])
      @title = "部门文件"
    else
      @public_infos = PublicInfo.where("info_type = '#{params[:info_type]}'").page(params[:page])
      @title = params[:info_type]
    end
  end

  def show
    @public_info = PublicInfo.find(params[:id])
  end
end

app/helpers/gov_info_helper.rb
module GovInfoHelper
end

app/helpers/gov_infos_helper.rb
module GovInfosHelper
end

app/helpers/home_page_helper.rb
module HomePageHelper
end

app/helpers/integritys_helper.rb
module IntegritysHelper
end

app/helpers/laws_helper.rb
module LawsHelper
end

app/helpers/organ_helper.rb
module OrganHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/public_infos_helper.rb
module PublicInfosHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/servers_helper.rb
module ServersHelper
end

app/views/public_infos/index.html.slim
div.container
  ul.breadcrumb
    li
      a href=root_path 首页
      span.divider \
    li.active 信息公开目录

  div.row
    div.span3
      ul.nav.nav-tabs.nav-stacked
        - @info_types.each do |info_type|
          li = link_to info_type, public_infos_path(:info_type => info_type)
    div.span9
      ul.nav.nav-tabs
        li.active
          a href="#" 
            strong = @title
      div
        table.table.table-striped width="100%" style="text-align:center;"
          tr
            td width="20%" 
              strong 索引号
            td width="35%" 
              strong 名称
            td width="15%" 
              strong 文号
            td width="15%" 
              strong 发文机关
            td width="15%" 
              strong 发文日期

          - @public_infos.each do |info|
            tr
              td = info.index_number
              td = link_to info.title, info
              td = info.file_number
              td = info.organ
              td = info.created_at.to_date
        div.pagination align="center"
          = paginate @public_infos

app/views/public_infos/show.html.slim
div.container
  div#content
    h2.title = @public_info.title
    .date = @public_info.created_at.to_formatted_s(:long)
    .content = sanitize @public_info.content