config/routes.rb
FoodSafeNet::Application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'

  devise_for :users

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  match '/laws/search' => 'laws#search'
  match '/servers/search_company' => 'servers#search_company'
  match '/servers/search_product' => 'servers#search_product'
  match 'organ' => 'organ#show'
  resources :comments, :only => [:create]
  resources :laws
  resources :gov_infos
  resources :public_infos
  resources :posts
  resources :products
  resources :reports, :only => [:index, :create, :query] do
    collection do
      post :query
    end
  end
  match 'servers' => 'servers#index'
  resources :integritys

  match '/signin' => 'sessions#new'

  root :to => "home_page#show"

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  # attr_accessible :title, :body
  belongs_to :user
  belongs_to :post

  attr_accessible :body, :user_id, :post_id
  validate :body, :presence => true
  validate :user_id, :presence => true
  validate :post_id, :presence => true
end

app/models/company.rb
class Company < ActiveRecord::Base
  attr_accessible :legal_person, :license_no, :license_project, :name, :produce_address, :register_address, :valid_for
end

app/models/gov_info.rb
class GovInfo < ActiveRecord::Base
  attr_accessible :content, :name, :info_type
end

app/models/integrity.rb
class Integrity < ActiveRecord::Base
  attr_accessible :content, :info_type, :title
end

app/models/law.rb
class Law < ActiveRecord::Base
  attr_accessible :content, :law_type, :title
end

app/models/organ.rb
class Organ < ActiveRecord::Base
  attr_accessible :content, :title
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :content, :title, :user_id

  has_many :comments
  belongs_to :user

  validate :content, :presence => true
  validate :title, :presence => true
  validate :user_id, :presence => true

end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :company_address, :company_name, :health_function, :license_no, :name
end

app/models/public_info.rb
class PublicInfo < ActiveRecord::Base
  attr_accessible :content, :file_number, :index_number, :organ, :title, :info_type
end

app/models/report.rb
class Report < ActiveRecord::Base
  attr_accessible :content, :no, :status, :title, :user_email, :user_name, :user_phone

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts, :dependent => :delete_all
  has_many :comments, :dependent => :delete_all

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :name, :password_confirmation, :remember_me
  # attr_accessible :title, :body
  validate :email, :presence => true, :uniqueness => true
  validate :password, :presence => true
  validate :name, :presence => true
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.order("created_at DESC").page params[:page]
  end

  def show
    @post = Post.find params[:id]
    @comments = @post.comments.order("created_at DESC").page(params[:page]).per(10)
    @comment = Comment.new
    @comment.post_id = @post.id
  end

  def edit
  end

  def new
    if user_signed_in?
      @post = Post.new
    else
      session["user_return_to"] = new_post_path
      redirect_to new_user_session_path
    end
  end

  def create
    post = Post.new
    post.assign_attributes params[:post]
    post.user_id = current_user.id
    post.save!
    redirect_to post_path post
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gov_info_helper.rb
module GovInfoHelper
end

app/helpers/gov_infos_helper.rb
module GovInfosHelper
end

app/helpers/home_page_helper.rb
module HomePageHelper
end

app/helpers/integritys_helper.rb
module IntegritysHelper
end

app/helpers/laws_helper.rb
module LawsHelper
end

app/helpers/organ_helper.rb
module OrganHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/servers_helper.rb
module ServersHelper
end

app/views/posts/edit.html.slim
h1 Posts#edit
p Find me in app/views/posts/edit.html.slim

app/views/posts/index.html.slim
div.container
	- if user_signed_in?
		a#new_post_link href=new_post_path
			button.btn.btn-primary#new_post_btn 发布新帖 
	- else
		|
			需要发帖?请
		= link_to "登录", new_user_session_path

	table.table.table-bordered.table-hover
		tr.info
			td 标题
			td 发帖用户
			td 发帖时间
			td 回帖数

		- @posts.each do |post|
			tr
				td
					= link_to post.title, post_path(post)
				td
					= post.user.name
				td
					= post.created_at.to_s(:db)
				td
					= post.comments.count
	
	.pagination align="center"
		= paginate @posts

app/views/posts/new.html.slim
.container
	h1 发布新帖

	div#post_edit_panel
		= form_for @post do |f|
			= f.label :title, "标题", :class => "post_edit_form_title"
			= f.text_field :title
			
			= f.label :content, "内容", :class => "post_edit_form_title"
			= f.cktext_area :content, :ckeditor => { :toolbar => "Basic" }

			= f.submit "发布", :class => "btn btn-primary", :id => "create_post_btn"

app/views/posts/show.html.slim
.container#post
	#post_info
		h3#post_title = @post.title
		|
			本帖由用户&nbsp
		strong = @post.user.name
		|
			&nbsp于&nbsp
		strong = @post.created_at.to_formatted_s(:db)
		|
			&nbsp发布

	#post_body
		= sanitize @post.content
	
	#comments
		- @comments.each do |comment|
			.comments
				strong = comment.user.name
				|
					&nbsp&nbsp
				strong = comment.created_at.to_formatted_s(:db)
				br
				= sanitize comment.body
				br
	.pagination align="center"
		= paginate @comments
	
	-if user_signed_in?
		#comment
			=form_for @comment, :url => comments_path(@comments), :method => :post do |f|
				= hidden_field_tag :post_id, @post.id
				= f.text_area :body, :placeholder => "回复本帖", :cols => 40, :rows => 8
				br
				= f.submit "回复", :class => "btn btn-primary"
	-else
		|
			需要回复？请
		= link_to "登录", new_user_session_path