config/routes.rb
FoodSafeNet::Application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'

  devise_for :users

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  match '/laws/search' => 'laws#search'
  match '/servers/search_company' => 'servers#search_company'
  match '/servers/search_product' => 'servers#search_product'
  match 'organ' => 'organ#show'
  resources :comments, :only => [:create]
  resources :laws
  resources :gov_infos
  resources :public_infos
  resources :posts
  resources :products
  resources :reports, :only => [:index, :create, :query] do
    collection do
      post :query
    end
  end
  match 'servers' => 'servers#index'
  resources :integritys

  match '/signin' => 'sessions#new'

  root :to => "home_page#show"

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  # attr_accessible :title, :body
  belongs_to :user
  belongs_to :post

  attr_accessible :body, :user_id, :post_id
  validate :body, :presence => true
  validate :user_id, :presence => true
  validate :post_id, :presence => true
end

app/models/company.rb
class Company < ActiveRecord::Base
  attr_accessible :legal_person, :license_no, :license_project, :name, :produce_address, :register_address, :valid_for
end

app/models/gov_info.rb
class GovInfo < ActiveRecord::Base
  attr_accessible :content, :name, :info_type
end

app/models/integrity.rb
class Integrity < ActiveRecord::Base
  attr_accessible :content, :info_type, :title
end

app/models/law.rb
class Law < ActiveRecord::Base
  attr_accessible :content, :law_type, :title
end

app/models/organ.rb
class Organ < ActiveRecord::Base
  attr_accessible :content, :title
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :content, :title, :user_id

  has_many :comments
  belongs_to :user

  validate :content, :presence => true
  validate :title, :presence => true
  validate :user_id, :presence => true

end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :company_address, :company_name, :health_function, :license_no, :name
end

app/models/public_info.rb
class PublicInfo < ActiveRecord::Base
  attr_accessible :content, :file_number, :index_number, :organ, :title, :info_type
end

app/models/report.rb
class Report < ActiveRecord::Base
  attr_accessible :content, :no, :status, :title, :user_email, :user_name, :user_phone

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts, :dependent => :delete_all
  has_many :comments, :dependent => :delete_all

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :name, :password_confirmation, :remember_me
  # attr_accessible :title, :body
  validate :email, :presence => true, :uniqueness => true
  validate :password, :presence => true
  validate :name, :presence => true
end

app/controllers/laws_controller.rb
#encoding: utf-8
class LawsController < ApplicationController
  def index
    @law_types = Law.select(:law_type).uniq.map(&:law_type)
    if params[:law_type] == nil
      @laws = Law.where("law_type = '相关法律'").page params[:page]
      @title = "相关法律"
    else
      @laws = Law.where("law_type = '" + params[:law_type]+ "'").page params[:page]
      @title = params[:law_type]
    end
  end

  def show
    @law = Law.find(params[:id])
  end

  def search
    @law_types = Law.select(:law_type).uniq.map(&:law_type)
    if(!params[:keyword].empty?)
      self.search_by_key_word params[:keyword]
    else
      if(!params[:keydate].empty?)
        self.search_by_key_date params[:keydate]
      else
        @laws = Law.where("law_type = '相关法律'").page params[:page]
      end
    end
    render 'index'
  end

  def search_by_key_word(keyword)
    spilited_word = keyword.split(//)
    query_string = "%"
    spilited_word.each do |char|
      query_string = query_string + char + "%"
    end
    @laws = Law.where("title LIKE '#{query_string}'").page params[:page]
  end

  def search_by_key_date(keydate)
    spilited_date = keydate.split("-");
    query_string = "%"
    spilited_date.each do |date|
      query_string = query_string + date + "%"
    end
    @laws = Law.where("created_at LIKE '#{query_string}'").page params[:page]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gov_info_helper.rb
module GovInfoHelper
end

app/helpers/gov_infos_helper.rb
module GovInfosHelper
end

app/helpers/home_page_helper.rb
module HomePageHelper
end

app/helpers/integritys_helper.rb
module IntegritysHelper
end

app/helpers/laws_helper.rb
module LawsHelper
end

app/helpers/organ_helper.rb
module OrganHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/servers_helper.rb
module ServersHelper
end

app/views/laws/index.html.slim
div.container
  ul.breadcrumb
    li
      a href=root_path 首页
      span.divider \
    li.active 法律法规 

  div.row
    div.span3
      ul.nav.nav-tabs.nav-stacked
        - @law_types.each do |law_type|
          li = link_to law_type, laws_path(:law_type => law_type) 

    div.span9
      ul.nav.nav-tabs
        li.active
          a href="#" 
            strong = @title
      div.row#search_form
        form.navbar-form.pull-right action="/laws/search" method="get"
          |
            关键字
          input.span2#keyword name="keyword" type="text"
          |
            &nbsp&nbsp&nbsp&nbsp时间
          input.span2#keydate name="keydate" type="text"
          |
            &nbsp&nbsp&nbsp&nbsp
          input.btn type="submit" value="搜索"
      br
      div#file_list
        table cell-padding="0" cell-spacing="0" width="100%"
          -@laws.each do |law|
            tr
              td
                = link_to law.title, law
              td align="right"
                = law.created_at.to_date

        div.pagination align="center"
          = paginate @laws

app/views/laws/show.html.slim
.container
  #content
    h2.title = @law.title
    .date = @law.created_at.to_formatted_s(:long)
    .content = sanitize @law.content